# Generated by Django 3.0.8 on 2020-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20200731_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Sheltered',
            field=models.DateTimeField(),
        ),
    ]
