# Generated by Django 3.0.8 on 2020-07-31 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20200731_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='difficulty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
